image: node:10.0.0

stages:
  - ver
  - init
  - deploy

ver:
  stage: ver
  script:
    - node --version
    - whoami
init:
  stage: init
  script:
    - npm cache clean
    - rm -rf node-modules
    - npm install
deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/happy-plate-academy--staging.git
    - git push heroku master
    - echo "Deployed to staging server"
  environment:
  name: staging
  url: https://happy-plate-academy--staging.herokuapp.com/
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/happy-plate-academy.git
    - git push heroku master
    - echo "Deployed to production server"
  environment:
  name: production
  url: https://happy-plate-academy.herokuapp.com/
  when: manual
  only:
    - master